#!/usr/bin/env bash


# update checking script for polybar
# written by Nathaniel Maia

BAR_ICON=""
ICON=/usr/share/icons/gnome/32x32/apps/system-software-update.png

# Infinite loop
for (( ; ; )); do

    # initial check
    count=$(checkupdates | wc -l)

    if hash notify-send >/dev/null 2>&1; then
        if [ $count -gt 50 ]; then
            notify-send -u critical -t 10000 -i $ICON \
                        "You really need to update soon" "$count New Packages Available"
        elif [ $count -gt 15 ]; then
            notify-send -u normal -t 10000 -i $ICON \
                        "You should update soon" "$count New Packages Available"
        elif [ $count -gt 1 ]; then
            notify-send -u low -t 10000 -i $ICON \
                        "$count New Packages Available"
        fi
    fi

    # while greater than 0 check every 8s
    while [ "$count" -gt 0 ]; do
        if [ $count -eq 1 ]; then
            echo "$count Update"
        elif [ $count -gt 1 ]; then
            echo "$count Updates"
        fi
        sleep 8
        count=$(checkupdates | wc -l)
    done

    # while 0, only check every 20 min
    while [ "$count" -eq 0 ]; do
        echo $BAR_ICON
        sleep 1200
        count=$(checkupdates | wc -l)
    done

done
