#!/bin/python

import  urllib.request, json

api_key = "771dd1bd80c16d56411ff27fa8ec0cf3"
map_lat = "43.5137"
map_long = "-79.8828"
units = "ca"
unit_key = "C"

weather = eval(str(urllib.request.urlopen("https://api.darksky.net/forecast/{}/{},{}?units={}&exclude=minutely,hourly,daily,alerts,flags".format(api_key, map_lat, map_long, units)).read())[2:-1])

summary = weather["currently"]["summary"]
temperature = int(float(weather["currently"]["temperature"]))

print("%s, %i °%s" % (summary, temperature, unit_key))
